### ISSUE TITLE
'clf.train' error = boolean index did not match indexed array along dimension 0

### ISSUE THREAD

**Issue by piango** [haesleinhuepf/apoc#1]
Hi
Great stuff.

I am running the apoc.pixelclassifer via a pipeline (spyder).

So I do as shown in one of your demos

```
features = "original_image gaussian_blur=7"
cl_filename = workingdir + foldername + '_classifier.cl'
apoc.erase_classifier(cl_filename)
clf = apoc.PixelClassifier(opencl_filename=cl_filename)
clf.train(features, label1, raw1,continue_training=True)
clf.train(features, label2, raw2,continue_training=True)
clf.train(features, label3, raw3,continue_training=True)
```

and I get this error when it attempts the second clf.train with label2 and raw2

I checked the images, and they seem fine.

any comment or advice will be great

thanks

```
------------------------------------------
  File "C:\Users\piango\AppData\Local\Temp/ipykernel_27864/2139741856.py", line 1, in <module>
    runfile('D:/OneDrive/Postdoc/GB_Lab/Analysis/quantification/organoid-segmentation-3D/predict_mesh_multipleobjects.py', wdir='D:/OneDrive/Postdoc/GB_Lab/Analysis/quantification/organoid-segmentation-3D')

  File "C:\Users\piango\anaconda3\envs\apoc\lib\site-packages\debugpy\_vendored\pydevd\_pydev_bundle\pydev_umd.py", line 167, in runfile
    execfile(filename, namespace)

  File "C:\Users\piango\anaconda3\envs\apoc\lib\site-packages\debugpy\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents + "\n", file, 'exec'), glob, loc)

  File "D:/OneDrive/Postdoc/GB_Lab/Analysis/quantification/organoid-segmentation-3D/predict_mesh_multipleobjects.py", line 54, in <module>
    clf.train(features,

  File "C:\Users\piango\anaconda3\envs\apoc\lib\site-packages\apoc\_pixel_classifier.py", line 63, in train
    X, y = self._to_np(features, ground_truth)

  File "C:\Users\piango\anaconda3\envs\apoc\lib\site-packages\apoc\_pixel_classifier.py", line 206, in _to_np
    X = X[mask]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 1221025 but corresponding boolean dimension is 1660594
--------------------------------------
```

**Comment by haesleinhuepf** [comment]
Hi @piango ,

great to see you here! Would you mind printing out the `shape`s of all images you pass to `clf.train`? `labelX` and `rawX` are supposed to have the same shape...

Best,
Robert

**Comment by haesleinhuepf** [comment]
... another difference to the [continue-training notebook](https://github.com/haesleinhuepf/apoc/blob/main/demo/demp_pixel_classifier_continue_training.ipynb) is that you are handing over `continue_training=True` also at the first training step. Could this be a problem?

**Comment by piango** [comment]
hi @haesleinhuepf 

yeah the shapes are different but the labels and raws are matching when i open them in napari (which is where i created the labels). This is weird. Maybe it is the way I am saving them

For your second comment. 
The console spits out == warnings.warn("Cannot continue training if it wasn't trained before. Will train from scratch instead.")

Im running apoc on 2 different machines. :)
And this is the first time I run on the second machine.

:)

**Comment by piango** [comment]
I am seeing now that it is a napari thing.
I will keep an update here

**Comment by piango** [comment]
Hi

this is open for too long.
And your suggestion was indeed the way.

Thanks again for this great tool

i will close this comment
:)
