### ISSUE TITLE
Question about the ObjectClassifer._select_features() docstring

### ISSUE THREAD

**Issue by kevinyamauchi** [haesleinhuepf/apoc#10]
Hello! Quick question about the `ObjectClassifer._select_features()` docstring.

https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L170-L188

It says that the returned `result` vectors (i.e., table columns) are length n+1 for n labels. When I use the debugger in [`test_object_classification()`](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/tests/test_object_classification.py#L2-L26), it looks like the `result` vectors have length 2. Since there are two label values (1 and 2 in `labels`), I would have expected them to be length 3. However, I can see why length 2 makes more sense. Which is correct? (working on the `TableRowClassifer` - just making sure I understand)

Thanks!

**Comment by haesleinhuepf** [comment]
Hi @kevinyamauchi ,

I'm just checking the code. It appears length = num_labels + 1 makes sense. [This line](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L202) extra adds a zero for the background and also the [neighbor count](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L205) contains a measurement for the background. Hence, I'm suspecting a bug. Maybe it's a good idea to write a test for this...

**Comment by haesleinhuepf** [comment]
... if this is indeed a bug, that would mean that background measurements are taken into account while training. We should remove the background-related measurements before training...
