### ISSUE TITLE
Remove 'return_numpy' from TableRowClassifier API

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/apoc#20]
I'd like to get rid of the `return_numpy` parameter [here](https://github.com/haesleinhuepf/apoc/blob/main/apoc/_table_row_classifier.py#L102), because:

Instead of this:
```
result_numpy = table_row_classifier.predict(table, return_numpy=True)
```
A user could run this:
```
result_numpy = np.asarray( table_row_classifier.predict(table) )
```
The second appears more standard to me and it simplifies the API. The other classifers also don't have this parameter.

@kevinyamauchi what do you think about this? Would it be ok to remove it immediately or shall we use some deprecation mechanism? I guess you and me might be the only users as this is relatively young functionality?

**Comment by kevinyamauchi** [comment]
Hello @haesleinhuepf ! That is fine with me. No deprecation notice required :)
