### ISSUE TITLE
Feature request: Print classifier info

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/apoc#23]
It would be nice if there were a function that could show some info about the classifier, e.g. the expexted dimensionality of input data, the used features, etc.

**Comment by haesleinhuepf** [comment]
Hi Johannes @jo-mueller ,

great idea! I just updated [this notebook](https://github.com/haesleinhuepf/apoc/blob/main/demo/mutlichannel_images.ipynb) demonstrating how this could be approached. Essentially, I suggest to build a `classifer.info()` function that uses this code snippet under the hood:
```
apoc._utils._read_something_from_opencl_file(cl_filename, "num_ground_truth_dimensions = ")
```

Let me know if you want to do this change and send a PR. Otherwise, I'm happy to implement it.

Best,
Robert

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

I have an implementation [here](https://github.com/jo-mueller/apoc/tree/add-info-function) - but it was much more complicated than I thought Before I start a PR maybe a quick discussion about whether what I did is the way to go or not:

- Printing information about the number of dimensions used for training requires the dimensions to be stored inside the .cl file
- This, in turn, requires a `classifier._dimensions` variable in the central `PixelClassifier` class
- This value can then be printed by a `classifier.info()` function
- I also added a check in `classifier.predict` that check whether the dimensions of the passed data matches the stored dimensions of the classifier and raises an Exception that points this out.
- I added a notebook for multi-channel segmentation that shows the `.info()` and the raised error

Should I start a PR? Tests are passing :)

**Comment by haesleinhuepf** [comment]
Hi Johannes @jo-mueller ,

awesome, thanks for working on this! One major hint: There is no need to write anything extra `dimensions` into the header. `num_ground_truth_dimensions` is already stored there, as mentioned above.

> Should I start a PR?

Yes! The code doesn't look very complicated though.

> * I also added a check in `classifier.predict` that check whether the dimensions of the passed data matches the stored dimensions of the classifier and raises an Exception that points this out.

Fantastic! I recently discovered a bug in this context, which you would resolve with that check.

> * This value can then be printed by a `classifier.info()` function

Would you mind also printing the other stuff that's written in the header? What about printing out the whole header? You wouldn't need the `_dimension` property then at all.

Before submitting the PR, please go through all changes in the code and check if they are really necessary, have good variable names and and are well described in comments. For example, I have no idea what `exc = sys.exc_info()` is doing, what the variable `exc` stands for and why it is necessary.

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

the output of the info function now looks like in [this notebook](https://github.com/jo-mueller/apoc/blob/add-info-function/demo/demo_pixel_classifier_multi_channel.ipynb). Is this how you envisioned it?

**Comment by haesleinhuepf** [comment]
Hey @jo-mueller ,

the notebook you linked does not contain any `clf.info()` output. Can you please check it again? Maybe it just needs to be executed and uploaded again.

Thanks!
Robert

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,just reran the notebook.

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

this output is wonderful:

```
Classifier type: PixelClassifier
--- Random forest info ---
Used features for training: original gaussian_blur=2 sobel_of_gaussian_blur=2
Training data dimensions: [2 x X x Y]
Maximum depth: 2
Number of ensembles: 100
Number of classes:  2
```

Do you want to send a PR?

Thanks!

Robert

**Comment by jo-mueller** [comment]
Here goes! 

#29
