### ISSUE TITLE
Train / predict from tables

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/apoc#8]
It should be pretty straight forward to rip out some parts of the ObjectClassifier and make a new classifier that does not use images, but table as input. 

That would also make this easier to implement:
* #7

**Comment by kevinyamauchi** [comment]
Hello again, @haesleinhuepf ! I am continuing the discussion from https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification/issues/10 on adding the ability to train/predict from a table.

To achieve training/prediction from a table, I propose the following:

1. Separate the setup code from the training code in `ObjectClassifier.train()`
    A. Create an `ObjectClassifer._train()` method [encapsulating the training code](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L47-L48). `ObjectClassifer._train()` would take the feature table, ground truth and `continue_training` as input arguments.
    B. Refactor `ObjectClassifer.train()` to do [the feature calculation](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L44-L45) and then pass the feature table and ground truth to `ObjectClassifer._train().
3. Separate the setup code from the prediction code in ObjectClassifer.predict
    A. Create an `ObjectClassifer._predict()` method encapsulating[ the prediction code](https://github.com/haesleinhuepf/apoc/blob/1a07fefbaccd0aa9fccfad1acaf38c873735f543/apoc/_object_classifier.py#L70-L83). `ObjectClassifer._predict()` would take the feature table as an input argument.
    B Refactor `ObjectClassifer.predict() to do the feature calculation and pass the features to `ObjectClassifer._predict()`.
4. Create an `ObjectClassifer.train_from_table()` that stores the feature names and passes the feature table to `ObjectClassifer._train()`.
4.  Create an `ObjectClassifer.predict_from_table()` method that takes a feature table, validates it contains the correct features and then passes them to `ObjectClassifier.predict()

What do you think?

In terms of maintaining compatibility with ImageJ, would it be possible to pass computed features as a table (e.g., the Measurement table)?

**Comment by haesleinhuepf** [comment]
Hey @kevinyamauchi ,

that sounds like an great plan! I would maybe not expose `train_from_table` in the `ObjectClassifier` but have a separate class `TableRowClassifier`.  My philosophy is: One class does exactly one sinple thing.
The `TableRowClassifier` takes a table (pandas Dataframe?) as constructor input and `train()` takes a ground-truth column-name. The `ObjectClassifier` might then use the `TableRowClassifier` under the hood. In that way, we could also solve #7.

> In terms of maintaining compatibility with ImageJ, would it be possible to pass computed features as a table (e.g., the Measurement table)?

On ImageJ side, [parts of the code](https://github.com/clij/clijx-accelerated-pixel-and-object-classification/blob/48f9673ef334a0c073272268f79ba7a6f1620368/src/main/java/net/haesleinhuepf/clijx/apoc/LabelFeatureGenerator.java#L221) already use `ResultsTable` so it might be easy to have the same change there. I'm CC-ing @SebastienTs who might be happy to see progress here 🌻 I'm happy to take care of the ImageJ side btw.

What do you think?

**Comment by kevinyamauchi** [comment]
Hey @haesleinhuepf , this all sounds good.

I agree that it is nice to have simple classes with simple jobs. In light of that, let's make a `TableRowClassifier`.

It feels to me like the `TableRowClassifier` should not take the data in the constructor. Rather, data would be passed via the `train` and `predict` methods (following the pattern of the current `PixelClassifer` and `ObjectClassifier`. If we do that, then we can  have the `ObjectClassifier` use the `TableRowClassifier` instead of the `PixelClassifier` under the hood.

**Comment by haesleinhuepf** [comment]
Yes, fully agreed! 🌞🌻
